package com.swyp.backend.analytics.entity;

public enum DomainEventType {
	APP_OPEN,
	PRODUCT_LIST_VIEW,
	PRODUCT_DETAIL_VIEW,
	RECIPE_IMPRESSION,
	HOLD_CREATE,
	HOLD_FAIL,
	NOTIFICATION_PERMISSION_RESULT,
	HOLD_CANCEL,
	HOLD_EXPIRE,
	PICKUP_COMPLETE,
	STOCK_RECONFIRM_TRIGGER,
	STOCK_RECONFIRM_YES,
	STOCK_RECONFIRM_NO,
	STOCK_RECONFIRM_DEFER,
	STOCK_ADJUST,
	OVERSELL_DETECTED,
	RECIPE_VIEW,
	RECIPE_FEEDBACK,
	PRODUCT_REGISTER,
	PRODUCT_SOLD_OUT
}
